### ISSUE TITLE
com.java package

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#10]
I'm pretty sure the point of package naming in Java is that you create your own namespace based on a domain name rather than using com.java.app.  

https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L1

**Comment by dionwiggins** [comment]
Changed to pdfextract.

See https://github.com/bitextor/pdf-extract/blob/optimizationwork/PDFExtract/src/pdfextract/PDFExtract.java

package pdfextract;
