### ISSUE TITLE
Hand-crafted spin loops for thread completion?

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#11]
The thread object has a `join()`.  There shouldn't be a busy loop here:

https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L353

**Comment by dionwiggins** [comment]
Changed to use Executor. 

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

Major changed made to Extract and  AddThreadExtract functions.
