### ISSUE TITLE
Sentence rejoining

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#14]
I know you're aware of this.  Rejoining lines into sentences is a major feature for PDF mining.

**Comment by dionwiggins** [comment]
Discussion underway with the team of integrating Language ID as an option.
Language ID is required to determine the correct approach to join sentences as many languages require language-specific sentence joining rules.
If we are going to take the overhead of Language ID, we can also get more out of it by returning the information to the calling application. By returning the % of content and the approximate word count in each language additional workflow can be added if the document has a mixture of languages. If the % is very low for one and high for the other it is probably just noise. If it is a reasonably even split between 2 languages, then this is a good indicator of a bilingual document that can be processed separately to extract and align content within the document.

**Comment by dionwiggins** [comment]
Planning going well on how to handle this.

1. Language ID full text
2. If more than 1 language, Language ID by page
3. If more than 1 language in page, Language ID by chunk
4. Sentence segment based on Language ID
5. Sentence join based on Language ID
6. Returned XML will have a header that contains language ID info and percentages for external processing in the workflow. This will include the default (dominant) language for the document.
7. Each span will have language ID info unless it is the default.
8. External workflow can take advantage of the Language ID in PDF extract to avoid reprocessing Language ID later in the workflow.

Scheduling for the work is under way.

**Comment by dionwiggins** [comment]
The language ID has been updated to CLD3 and it is now using Poppler. New more efficient structure in output.
Sentence joining is fully implemented but after discussion with Philipp decided that it is more appropriate to sentence segment outside as the same sentence segmenter that is used in other parts of Paracrawl should be used. Language ID is embedded at a paragraph level.
