### ISSUE TITLE
pdf-extract in warc2htmlwarc uses >1 processor

### ISSUE THREAD

**Issue by wwaites** [bitextor/pdf-extract#17]
Watching with top shows it using up to 200% of a processor. In the envisaged production pipeline, this is not ideal as it might lead to oversubscription of CPU resources. On the other hand, the OS scheduler ought to ration the CPU to provide sensible concurrency effectively limiting to 100% on a loaded machine.

**Comment by dionwiggins** [comment]
We are tracing it now. We don't have the means to reproduce the issue but suspect that the Apache PDFBox may be spinning up a thread. We are investigating at present.

**Comment by lpla** [comment]
Any progress on this?

**Comment by dionwiggins** [comment]
Hi Leo,
 
We are moving to Poppler. Mui is aiming to finish the full rewrite for Poppler, with language ID, sentence join and the relevant document adjustments within this week. As such, we don’t plan to fix this issue as we will discontinue using PDFBox.
 
Regards,

Dion Wiggins 
Founder and CTO
Omniscien Technologies

Phone: +66 (8) 7086 3353
Fax: +66 (2) 662 4728, +66 (2) 662 4727
Skype: dionwiggins
Email: dion.wiggins@omniscien.com
Web: http://www.omniscien.com
 
NOTICE: This e-mail (including all information transmitted with it) is for the intended addressee only. It may contain information that is confidential, proprietary and/or legally privileged. No confidentiality, ownership right or privilege is waived or lost by any mistransmission, redirection or interception.  No one other than the intended addressee may read, print, store, copy, forward or act in reliance upon this e-mail.  If you are not the intended addressee: (a) any use, dissemination, printing or copying of this e-mail is strictly prohibited and may be a breach of confidence, and (b) kindly notify the sender by e-mail immediately and delete and destroy all copies of this e-mail in your possession.

**Comment by dionwiggins** [comment]
New version using Poppler makes the PDFBox version no longer relevant. Closing this one.
