### ISSUE TITLE
Document new dependencies

### ISSUE THREAD

**Issue by lpla** [bitextor/pdf-extract#21]
Given that now 'pdfbox' is out of the project and new dependencies are included, we should ensure that licenses are proper and most of the code can be maintained and debugged. So, please update this file https://github.com/bitextor/pdf-extract/blob/master/INSTALL.md with new dependencies (https://github.com/bitextor/pdf-extract/tree/master/PDFExtract/lib) and their licenses.

Specially 'cld3-java.jar' which is strangely imported in Java as
`import cz.vutbr.fit.knot.NNetLanguageIdentifierWrapper;`

**Comment by MickeyVI** [comment]
The dependency and pre-requisite information has been updated.

 https://github.com/bitextor/pdf-extract/blob/poppler-rewrite/INSTALL.md
