### ISSUE TITLE
Branch poppler-rewrite does not extract any text

### ISSUE THREAD

**Issue by lpla** [bitextor/pdf-extract#25]
I tested `poppler-rewrite` included java (`runnable-jar/PDFExtract.jar`) in a machine with Ubuntu 16.04 (as of today, the only OS in which it works because #22 ) with several PDFs I own and some Internet Archive files and I only get:

```
<html>
<head>
<defaultLang abbr="en" />
<languages>
</languages>
</head>
<body>
<div id="page0" class="page">
</div>
</body>
</html>
```

Is it just me? Master code (based on pdfbox) works.

**Comment by dionwiggins** [comment]
Please provide the PDFs. We have tested about 20K files without issue so need to reproduce on the file that you are having an issue with. It could be protected or a number of other reasons that it returns empty. With the sample we can diagnose.

**Comment by lpla** [comment]
This one, for example, extracts text with `master` code (pdf-box) but nothing in `poppler-rewrite`: https://www.dlsi.ua.es//~mlf/docum/forcada16j.pdf

**Comment by lpla** [comment]
The command I use is:
```
~/pdf-extract$ java -jar runnable-jar/PDFExtract.jar -I ~/forcada16j.pdf -O test
```

**Comment by dionwiggins** [comment]
This is resolved in the latest release above.
