### ISSUE TITLE
Make dependency installation optional in poppler-rewrite setup.sh

### ISSUE THREAD

**Issue by lpla** [bitextor/pdf-extract#27]
Trying out `pdf-extract/setup.sh`, it looks like it always run all the `apt` or dependency related commands, like compiling and installing `protobuf`. This should be optional. For example, calling `bash setup.sh compile` could only compile/build `cld3`, `cld3-java` and `pdf-extract`, which are also tasks without `sudo`.

This is necessary to make the `python-pdfextract` wrapper working, and then, `bitextor-warc2htmlwarc` efficient calls to `pdf-extract`.

**Comment by dionwiggins** [comment]
My understanding is that protobuf is needed in order for Java to talk to CLD3. I will verify with Mui.

**Comment by lpla** [comment]
I know it is a needed dependency, but I don't always need to download, compile and install git protobuf in the system. For example, when I need to run `setup.sh` simply for the Java build commands, or when I want to use a protobuf version from `apt` or any other package manager because I don't have sudo permissions. The same applies for the `apt install` calls in `setup.sh`.

**Comment by dionwiggins** [comment]
Mui has implemented already. Closing
