### ISSUE TITLE
pdf-extract timeout option

### ISSUE THREAD

**Issue by lpla** [bitextor/pdf-extract#30]
I found some small PDF documents with some pages that contain (or pdftohtml detects as) many images that makes pdf-extract go dramatically slow. These PDFs are still running `pdftohtml` command (from `poppler-rewrite`) in a server after 2 days:

[pdf-37183335900956442200.3957922402592299.pdf](https://github.com/bitextor/pdf-extract/files/4292058/pdf-37183335900956442200.3957922402592299.pdf)
[pdf-88372559814386653860.962414730293883.pdf](https://github.com/bitextor/pdf-extract/files/4292059/pdf-88372559814386653860.962414730293883.pdf)

Workaround for this specific case could be simply discarding a page with a number of images higher than a threshold, or a timeout that could cover other kind of issues with Poppler.

**Comment by dionwiggins** [comment]
Thanks. We could also work on removing the images from the PDF before processing as a workaround. Interesting feedback. I will have Mui investigate.

**Comment by lpla** [comment]
I see you implemented it, but probably 30 seconds default is too low. 10 minutes should be a maximum we don't want to reach when processing a PDF.

**Comment by dionwiggins** [comment]
Changed to 10 minutes as default. Closing.
