### ISSUE TITLE
Why can't bold have tags inside it?

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#39]
What if I make things **bold _and italic_**?
https://github.com/bitextor/pdf-extract/blob/4ad28a23817851355ba65b6b4699a8f01b2cb760/src/pdfextract/PDFExtract.java#L61

**Comment by dionwiggins** [comment]
Why would you want bold or italic? It is extracting plain text. Plain text does not have bold or italic.

**Comment by kpu** [comment]
I don't know why you want to detect bold in a PDF extractor.  If you don't need to, remove the code.  But you have one right now and it has a bug.
