### ISSUE TITLE
Are you using a HashMap on sequential integers keys?

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#5]
I only did a cursory read of this code, but it looks like you're using a HashMap whose keys are consecutive integers?  

https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L643
https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L644

**Comment by kpu** [comment]
Same question for `model`?
https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L745

https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L746

**Comment by dionwiggins** [comment]
Resolved as part of optimization rewrite. See https://github.com/bitextor/pdf-extract/blob/460c3f054bf0b10a4dacd7aad9d7d4240fbf7db4/PDFExtract/src/pdfextract/PDFExtract.java#L742

Please ignore # links above - this was in error.
