### ISSUE TITLE
Bad redirection of kenlm stderr

### ISSUE THREAD

**Issue by Proyag** [bitextor/pdf-extract#50]
https://github.com/bitextor/pdf-extract/blob/b24fc2df0e7b3e11a1d08cecd7560fe6b83ef2f8/src/pdfextract/SentenceJoin.java#L92 redirects sentence-join subprocess stderr to stdout.

sentence-join stderr gets stuff like

> This binary file contains trie with quantization and array-compressed pointers.

from kenlm.

https://github.com/bitextor/pdf-extract/blob/b24fc2df0e7b3e11a1d08cecd7560fe6b83ef2f8/src/pdfextract/SentenceJoin.java#L103-L107 interprets these outputs as errors starting sentence-join and throws an exception that looks like:

> java.lang.Exception: This binary file contains This binary file contains trie with quantization and array-compressed pointerstrie with quantization and array-compressed pointers..
> 
>         at pdfextract.SentenceJoin.start(SentenceJoin.java:106)
>         at pdfextract.PDFExtract.sentenceJoin(PDFExtract.java:1579)
>         at pdfextract.PDFExtract.sentenceJoin(PDFExtract.java:1083)
>         at pdfextract.PDFExtract.Extract(PDFExtract.java:384)

**Comment by ramoelee** [comment]
Hi @Proyag , 
appreciate your help to provide the pdf file that hit the above error.

Thank you.

**Comment by Proyag** [comment]
I can't reproduce this deterministically, so my diagnosis was probably over-simplified, but this pops up when processing large numbers of files, for example while running many instances of [bitextor-warc2htmlwarc.py](https://github.com/bitextor/bitextor/blob/master/bitextor-warc2htmlwarc.py) in parallel.

I can work around this issue for now by redirecting kenlm error output to /dev/null [here](https://github.com/Proyag/pdf-extract/blob/28abad29918b6b456d0c6e282237447ac1725ef6/sentence-join/sentence-join.py#L29) - I'll produce a reproducible example if I run into it again.
