### ISSUE TITLE
Over 2M of trash files produced while crawling

### ISSUE THREAD

**Issue by mbanon** [bitextor/pdf-extract#56]
Hi, I've been running Bitextor, branch snake_performance (mentioning  @lpla in case he is needed here)

After it finished, I noticed that 2.162.294 (!!!) files, with names being `nonsense-{numbers}.png`, appeared in my crawling directory:

![Captura de pantalla_2020-12-18_13-27-43](https://user-images.githubusercontent.com/34235767/102614643-e02bbe00-4134-11eb-9dae-351c7d89c3a9.png)

After some investigation, I found this line: https://github.com/bitextor/pdf-extract/blob/d4fe244408c55c1b881e62ccee75780e74930dda/src/pdfextract/PDFToHtml.java#L194 , that is suspicious...

This needs to be fixed asap...

**Comment by mbanon** [comment]
I ran another instance of Bitextor that created almost 9M files...
![Captura de pantalla_2020-12-20_11-51-34](https://user-images.githubusercontent.com/34235767/102711519-9836a380-42ba-11eb-8e44-877b3ebdcb50.png)

**Comment by mbanon** [comment]
And the suspicious command , caught in htop:
![htop](https://user-images.githubusercontent.com/34235767/102711720-134c8980-42bc-11eb-85dd-9b4430eb7756.png)

(They appear here and there, each one running for a few seconds)

**Comment by ramoelee** [comment]
Hi @mbanon
please help to update the source code and reinstall PDFExtract.jar for resolve the issue.

Thanks

**Comment by mbanon** [comment]
Ok, I applied the fix and it's running now.

Will close when Bitextor finishes (with no trash files :) ) 
Thanks!
