### ISSUE TITLE
Sentence join fails when using a batch file

### ISSUE THREAD

**Issue by zuny26** [bitextor/pdf-extract#57]
When using PDFExtract-2.0.jar with `-B` option to process a list of files, sentence join model is only applied to the first file. After that, PDFExtract writes the following error message to stdout for each line that is passed to sentence join: 
```
execute sentence join [es] failed. ... ,Stream closed 
```
(where `...` is the content of the line)

Processing same files separately works fine, so it looks like sentence join process is closed after finishing with the first file.

My config file is: [pdfextract.json.txt](https://github.com/bitextor/pdf-extract/files/6021897/pdfextract.json.txt)
Sentence join models downloaded from http://data.statmt.org/paracrawl/sentence-join/
The PDFs that I tested with are: [one](https://ssyf.ua.es/es/seleccionpas/documentos/plazas-temporales/2021/i20/convocatoria.pdf) and [two](https://ssyf.ua.es/es/seleccionpas/documentos/plazas-temporales/2021/i17/convocatoria.pdf)

**Comment by ramoelee** [comment]
Hi @zuny26 , 
please help to update the source code and reinstall PDFExtract.jar for resolve the issue.

Thanks

**Comment by zuny26** [comment]
Hi @ramoelee
Thank you, the issue is solved now for the batch file use case. However if this function is used:
https://github.com/bitextor/pdf-extract/blob/425afb6fe2d42fa908240ae8784c631aac555e0e/src/pdfextract/PDFExtract.java#L356
the issue still persists. It would be nice to fix this function as well, because this is what we use for our [python wrapper](https://github.com/bitextor/python-pdfextract) and c++ wrapper (currently in development)

**Comment by ramoelee** [comment]
Hi @zuny26 ,
please help to update the source code and reinstall PDFExtract.jar for resolve the issue.

Thanks

**Comment by zuny26** [comment]
Yes, it seems to be working now, thank you!
The only remaining problem that I see is that when verbose mode is activated, PDFExtract is printing a lot of lines that just say "null"

**Comment by ramoelee** [comment]
Hi @zuny26 ,
please help to update the source code and reinstall PDFExtract.jar for resolve the issue.

Thanks
