### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#6]
The code is really hard to read on github presumably due to a mix of spaces and tabs to indent.  Can you make it more readable perhaps by mapping tabs to spaces according to your definition?

https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java

**Comment by dionwiggins** [comment]
Cleaned up.
