### ISSUE TITLE
ArrayList appears to exist solely to have its minimum taken

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#7]
The `objlinetop` object appears to exist as an ArrayList solely so that later code can take the minimum value.  
https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L942
Replace with a double and take the minimum on the fly.  Same for many of the other objects in this function.

**Comment by dionwiggins** [comment]
Data is no longer kept in the collection as part of optimizations. The rewrite has removed this issue. Min value is calculated on the fly.
