### ISSUE TITLE
Use git properly

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#9]
I told Omniscien to use descriptive commit messages in https://github.com/paracrawl/Domain_Adaptation/issues/27

**Comment by dionwiggins** [comment]
We are trying and learning :)

**Comment by kpu** [comment]
Thank you for using git commits rather than web file uploads.  

A commit message should match what was changed in the code by that commit.  So for example: https://github.com/bitextor/pdf-extract/commit/63de09f66005d7422eaf0d4033ebb62d76da6024 could be described as "removed whitespace from blank lines".  It appears to be a (well-written) summary of commits that happened before it.  

Going forward, please describe each commit as you go.  This makes it easier to understand what the author was trying to do when a line of code is written.  And it narrows the set of code one has to examine to confirm that an issue was fixed.

**Comment by dionwiggins** [comment]
Noted and have discussed with the developer.
